### PR TITLE
Strip comments from code before checking syntax

### PR DESCRIPTION
**Pull request by iPhilip**
I am suggesting the following changes to avoid having text in the comments affect the result of the syntax check.

References:

- [Ask for Help Post](https://www.autohotkey.com/boards/viewtopic.php?f=76&t=112426)
- [Wish List Post](https://www.autohotkey.com/boards/viewtopic.php?f=13&t=112487)

### CODE REVIEW

**Comment by white-gthb** [comment]
Right below the code you want to change, you can see that information in the comment is actually being used.

It is documented [here](https://www.autohotkey.com/docs/v2/Program.htm#launcher-criteria) in the Help:

> Criteria can be specified within the script by using the [#Requires](https://www.autohotkey.com/docs/v2/lib/_Requires.htm) directive, either as a requirement (if supported by the target AutoHotkey version), or appended to the directive as a `comment` beginning with "prefer" and ending with a full stop or line ending.

Furthermore, the code isn't very good. A semicolon with a leading non space character is no comment (also wrong in existing code). Your code seems to assume that /* and */ can't be both on the same line and that code can follow behind */. See [here](https://www.autohotkey.com/docs/v2/Language.htm#comments) in the Help. And your code assumes a semicolon can comment out */

**Comment by iPhilip** [comment]
> Right below the code you want to change, you can see that information in the comment is actually being used.
> 
I agree. As I mentioned above, it would be ideal if that wasn't the case.
> It is documented [here](https://www.autohotkey.com/docs/v2/Program.htm#launcher-criteria) in the Help:
> 
> > Criteria can be specified within the script by using the [#Requires](https://www.autohotkey.com/docs/v2/lib/_Requires.htm) directive, either as a requirement (if supported by the target AutoHotkey version), or appended to the directive as a `comment` beginning with "prefer" and ending with a full stop or line ending.
> 
That's not the type of comment I was trying to address, though my code strips out the "prefer comment" so that's not good.
> A semicolon with a leading non space character is no comment (also wrong in existing code).
>
I am confused by this as I don't see where I am making that assumption. Leading tabs are allowed in v1 and v2. Where is it wrong in the existing code?
> Your code seems to assume that /* and */ can't be both on the same line
>
I agree. It was my mistake.
> and that code can follow behind */. See [here](https://www.autohotkey.com/docs/v2/Language.htm#comments) in the Help.
>
It can. This works in v1 and v2.
```
/*
Comment
*/  MsgBox
```
> And your code assumes a semicolon can comment out */
>
That's also my mistake.

When I looked further into the differences between v1 and v2 comments, I realize that a script designed to strip comments needs to know whether the file represents v1 or v2 code _a priori_. Thus, what I am trying to do is not possible.

In the end, as stated [here](https://www.autohotkey.com/docs/v2/Program.htm#launcher),

> **Note: Declaring the required version with #Requires at the top of the main file eliminates any ambiguity.**

**Comment by white-gthb** [comment]
> > Right below the code you want to change, you can see that information in the comment is actually being used.
> 
> I agree. As I mentioned above, it would be ideal if that wasn't the case.

It already happened. You cannot change history, can you?

> > A semicolon with a leading non space character is no comment (also wrong in existing code).
> 
> I am confused by this as I don't see where I am making that assumption. Leading tabs are allowed in v1 and v2. Where is it wrong in the existing code?

I meant "non white space", so tabs included. Sorry for my poor wording. It concerns this line:
```ahk
        Line := RegExReplace(A_LoopReadLine, "[ `t]*;.*")
````
There is no comment for example in a line like this: `msgbox "1;23"`

> > and that code can follow behind */. See [here](https://www.autohotkey.com/docs/v2/Language.htm#comments) in the Help.
> 
> It can. This works in v1 and v2.
> 
> ```
> /*
> Comment
> */  MsgBox
> ```
You are right and this is described in the Help. Code can follow if */ is at the start of a line. But not if */ is at the end of a comment line (version 2), which your code assumes doesn't happen.

**Comment by iPhilip** [comment]
> It already happened. You cannot change history, can you?
> 
I am not trying to change history. I am just trying to contribute a change so that others will benefit from it. As I mentioned above, I have now determined that stripping comments is not possible without knowing if the file represents v1 or v2 code _a priori_ so I won't be pursuing this any longer.
> 
> I meant "non white space", so tabs included. Sorry for my poor wording. It concerns this line:
> 
> ```ahk
>         Line := RegExReplace(A_LoopReadLine, "[ `t]*;.*")
> ```
> 
You are right. That line in _my code_ should have been
```ahk
        Line := RegExReplace(A_LoopReadLine, "[ `t]+;.*")  ; Note the "+"
```
I don't see it in the existing code.
> You are right and this is described in the Help. Code can follow if */ is at the start of a line.
>
As far as I can tell, it's not described in the Help. Perhaps, it should.

**Comment by white-gthb** [comment]
> > It already happened. You cannot change history, can you?
> 
> I am not trying to change history. I am just trying to contribute a change so that others will benefit from it. ..

Please don't take it the wrong way. I am very tired at the moment and was very direct. I was constantly hoping you wouldn't take what I said the wrong way. I appreciatie your efforts and I'm exactly like you, just trying to contribute.

> You are right. That line in _my code_ should have been
> 
> ```ahk
>         Line := RegExReplace(A_LoopReadLine, "[ `t]+;.*")  ; Note the "+"
> ```
> 
> I don't see it in the existing code.

Just below the code you wanted to change:
https://github.com/AutoHotkey/AutoHotkeyUX/blob/69d902c72c52b17256e71f0caf4726e90ca29762/launcher.ahk#L65-L66

This substitutes strings like "; prefer" or  ";whatever" anywhere, regardless whether or not it is preceded by white space.

> > You are right and this is described in the Help. Code can follow if */ is at the start of a line.
> 
> As far as I can tell, it's not described in the Help. Perhaps, it should.

It is described [here](https://www.autohotkey.com/docs/v2/Language.htm#comments):
> ... `*/` can appear only at the `start` or `end` of a line.

**Comment by Lexikos** [comment]
The *syntax check* is (optionally) performed using a very complicated regex pattern, which already takes comments and continuation syntax into account.

As is evident at a glance of the source code, the `#Requires` check is done separately, and (as has been noted) explicitly permits the directive to be contained by a comment. One reason for this is to permit its use with AutoHotkey versions that predate the implementation of `#Requires`.

If you have a comment including the directive, your script was obviously written after the directive was implemented. You can easily avoid the false detection by including the appropriate directive (`#Requires AutoHotkey v1.1`) at the top of the script. I believe this is an acceptable limitation.

If there are other examples where code within a comment *erroneously* affects the result of the syntax check (not the `#Requires` check), those might be bugs.

**Pull request closed without merging**
