### PR TITLE
Update Launch.ahk

### PR DESCRIPTION
**Pull request by RaptorX**
Fix "v" not being optional as per documentation

### CODE REVIEW

**Comment by white-gthb** [comment]
1) Is capital letter V allowed too?
2) Isn't that line meant to determine version number?
Consider for example this line from Help page https://www.autohotkey.com/docs/v2/Program.htm:
 > #Requires AutoHotkey v1.1.35 ; prefer 64-bit, Unicode.  More comments.

If I read the code correctly, variable v will become "64-bit," and later on in the function GetRequiredOrPreferredExe will check the registry key HKCU\Software\AutoHotkey\Launcher\v64 for installed version information...

And there are more problems, see issue https://github.com/AutoHotkey/AutoHotkeyUX/issues/6, so I think a larger chunk of code needs a do-over.

**Comment by RaptorX** [comment]
Not really. 
The `v` doesnt determine the bitnes... you specify that with either `32-bit` or `64-bit`.
The example you presented has that **commented out**. For that reason the code could be run with v1.1.35 32 **or** 64 bit...

this would lock the bitnes:

```
; this code would NOT run with v1.1.35 32-bit as I just locked it to 64-bit.
#Requires AutoHotkey v1.1.35 64-bit
```

In any case, the `v` is supposed to be optional and I would assume it should be `case insensitive` as AutoHotkey defaults to that.

I didnt touch the comparison operands as I was only aware of the `v` not being optional.
Will take a look at the other bugs later.

**Comment by white-gthb** [comment]
> The example you presented has that **commented out**.

What are you talking about? Your commit changes the interpretation of the refer directive which is always a comment. As explained in the mentioned Help page in the line above the example:

> Criteria can be specified within the script by using the [#Requires](https://www.autohotkey.com/docs/v2/lib/_Requires.htm) directive, either as a requirement (if supported by the target AutoHotkey version), or appended to the directive as a comment beginning with "prefer" and ending with a full stop or line ending. For example:

**Comment by Lexikos** [comment]
See #6 and a8f202f.

> Your commit changes the interpretation of the refer directive which is always a comment. 

The `prefer` variable was a combination of *both sides* of `; prefer`. It is not always a comment.

The #Requires directive literally supports *An optional letter "v"* as written. It does not support a capital V. I chose this (basically on a whim) to enforce a little consistency. I always prefer it in lowercase. However, there's no harm in the launcher allowing a capital V; it will just run AutoHotkey, which will (currently) raise an error.

**Pull request closed without merging**
